import {MAKERS,ITEMS,STATES,insertItem,joinItems,normalizationView,parseCents,createTransfer,transferAction,ETL_SAMPLE,transformEmployees} from './models.mjs';
import {QUERY_EXAMPLES} from './sql-core.mjs';
import {createSQLClient} from './sql-client.mjs';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const activities=[
  {id:'keys',number:'01',name:'Connect the rows',short:'Keys & joins',source:'Slides 21–22',description:'Give every item an identity. Follow its foreign key to a maker, and test what the database should reject.',tiles:['Items','maker_id','Makers'],prompt:'Try an orphan maker with the foreign key enabled. Then disable it and insert the orphan. How do INNER JOIN and LEFT JOIN differ?'},
  {id:'normalization',number:'02',name:'Store each fact once',short:'Normalization',source:'Slides 25–31',description:'Walk the lecture’s restaurant tables from repeating groups to 3NF. Move Alice #1 and uncover an update anomaly.',tiles:['1NF','2NF','3NF'],prompt:'In 1NF, update just one Alice #1 row. Then switch to 3NF and make the same move. Why does Alice #3 stay in Wyoming?'},
  {id:'queries',number:'03',name:'Ask the database',short:'SQL sandbox',source:'Slides 33–39',description:'Edit real SQL and run it against a small restaurant and inventory database in your browser.',tiles:['SQL','SQLite','rows'],prompt:'Run the JOIN example. Add WHERE e.employee_id = 1 before ORDER BY. Then try an INSERT, UPDATE, or DELETE and inspect the result.'},
  {id:'transactions',number:'04',name:'Finish the whole transfer',short:'Transactions',source:'Slide 23',description:'Step through a transfer. Compare private changes with committed balances, then commit or roll back.',tiles:['BEGIN','updates','COMMIT'],prompt:'Enable the simulated credit failure. Begin, debit, then credit. What happened to the money that appeared to leave checking?'},
  {id:'etl',number:'05',name:'Turn JSON into rows',short:'JSON → SQL',source:'Slides 50–51',description:'Clean and validate an editable batch, inspect rejected records, and load accepted rows with bound SQL parameters.',tiles:['JSON','validate','SQL'],prompt:'Load the sample twice. The second load conflicts with stored IDs. Does any part of that second batch remain?'}
];
const params=new URLSearchParams(location.search);let current=activities.find(activity=>activity.id===params.get('activity'))?.id??null;
let client=null,toastTimer,renderGeneration=0;
const initial={
 keys:()=>({items:ITEMS.map(row=>({...row})),id:'12344',name:'Gear A',quantity:'5',maker:'2',enforce:true,join:'inner',highlight:2,message:'Start with a valid row, or try a duplicate ID or missing maker.',error:false}),
 normalization:()=>({form:1,update:'none',target:51}),
 transactions:()=>({model:createTransfer(),amount:'25.00',failCredit:false}),
 queries:()=>({sql:QUERY_EXAMPLES[0].sql,example:'select',ready:false,busy:false}),
 etl:()=>({raw:ETL_SAMPLE,trimNames:true,normalizeStates:true,duplicates:'skip',ready:false,busy:false,imported:{columns:['employee_id','name','state_code'],values:[]},message:'Validate the source, then load the accepted rows.',error:false})
};
const states=Object.fromEntries(Object.entries(initial).map(([key,create])=>[key,create()]));
function notify(message){$('#toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').textContent='';},4000);}
function cell(value){return value===null?'<span class="null">NULL</span>':esc(value);}
function table(columns,rows,{highlight=()=>false,warning=()=>false}={}){
 return `<div class="table-wrap"><table><thead><tr>${columns.map(column=>`<th scope="col">${esc(column)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map((row,index)=>`<tr class="${warning(row,index)?'warning':highlight(row,index)?'highlight':''}">${row.map(value=>`<td>${cell(value)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}" class="empty">No rows.</td></tr>`}</tbody></table></div>`;
}
function modelTable(name,columns,records,options={}){return `<div class="table-card"><h3>${name}</h3>${table(columns,records.map(record=>columns.map(column=>record[column])),options)}</div>`;}
function result(html){const focused=document.activeElement?.id;$('#results').innerHTML=html;if(focused)document.getElementById(focused)?.focus({preventScroll:true});}
function source(url,label){return `<p class="source-link">Reference: <a href="${url}" target="_blank" rel="noopener">${label} ↗</a></p>`;}
function gallery(){
 $('#main').innerHTML=`<section class="gallery-header"><div><p class="eyebrow">Lecture 05 / Student playground</p><h1>Make a change.<br>See the relationship.</h1><p class="intro">Five experiments in relational data. Connect records, repair a design, and run SQL against a database you can reset.</p></div><div class="stamp">Small datasets.<br>Visible consequences.<br>A separate link for every activity.</div></section><div class="gallery">${activities.map(activity=>`<a class="activity-card" href="?activity=${activity.id}"><span class="number">${activity.number} / ${activity.source}</span><div class="mini" aria-hidden="true">${activity.tiles.map((tile,index)=>`${index?'<span class="arrow">→</span>':''}<span class="tile ${index===1?'orange':index===2?'blue':''}">${tile}</span>`).join('')}</div><h2>${activity.name}</h2><p>${activity.description}</p><span class="card-link">Open interactive<span>↗</span></span></a>`).join('')}</div><p class="section-note">The sandbox and ETL loader execute SQLite locally. The other activities are labeled teaching models. Data stays in this tab; refreshing or leaving an activity resets its experiment.</p>`;
}
function render(){
 renderGeneration+=1;client?.close();client=null;
 if(!current){gallery();return;}
 const activity=activities.find(item=>item.id===current);
 document.title=`${activity.short} · Lecture 05 interactive lab`;
 $('#main').innerHTML=`<a class="back" href="index.html">← All SQL interactives</a><div class="activity-heading"><div><p class="eyebrow" style="margin-top:26px;margin-bottom:8px">${activity.number} / ${activity.source} / ${['queries','etl'].includes(current)?'Local SQLite':'Classroom model'}</p><h1>${activity.name}</h1><p class="intro">${activity.description}</p></div><div class="heading-tools"><button id="reset">Reset activity</button><button id="copy-link">Copy activity link</button></div></div><nav class="activity-tabs" aria-label="Activities">${activities.map(item=>`<a href="?activity=${item.id}" ${item.id===current?'aria-current="page"':''}>${item.short}</a>`).join('')}</nav><div class="workspace ${current==='queries'?'query-workspace':current==='etl'?'wide':''}"><section class="panel" id="controls" aria-label="Activity controls"></section><div class="result-column" id="results" aria-label="Activity results"></div></div><aside class="prompt"><strong>Try this</strong>${activity.prompt}</aside>`;
 $('#reset').onclick=()=>{states[current]=initial[current]();render();notify('Activity and data reset.');};
 $('#copy-link').onclick=async()=>{const url=new URL('index.html',location.href);url.searchParams.set('activity',current);try{await navigator.clipboard.writeText(url.href);notify('Direct activity link copied.');}catch{const field=document.createElement('input');field.value=url.href;field.setAttribute('aria-label','Activity link — select and copy');field.style.width='100%';$('#controls').prepend(field);field.focus();field.select();notify('Copy the selected link in the controls.');}};
 renderers[current]();
}

function renderKeys(){
 const s=states.keys;
 $('#controls').innerHTML=`<h2>Insert an inventory item</h2><div class="presets"><button data-preset="valid">Valid row</button><button data-preset="duplicate">Duplicate ID</button><button data-preset="orphan">Orphan maker</button></div><label class="field"><span>item_id · primary key</span><input id="item-id" inputmode="numeric" value="${esc(s.id)}" maxlength="10"></label><label class="field"><span>item_name</span><input id="item-name" value="${esc(s.name)}" maxlength="80"></label><label class="field"><span>item_qty</span><input id="quantity" inputmode="numeric" value="${esc(s.quantity)}" maxlength="8"></label><label class="field"><span>maker_id · foreign key</span><select id="maker">${[...MAKERS,{maker_id:99,maker:'No matching maker'}].map(row=>`<option value="${row.maker_id}" ${String(row.maker_id)===s.maker?'selected':''}>${row.maker_id} · ${esc(row.maker)}</option>`).join('')}</select></label><label class="check"><input id="enforce-fk" type="checkbox" ${s.enforce?'checked':''}>Enforce the maker foreign key</label><button class="primary" id="insert-item">Try INSERT</button><hr class="control-divider"><label class="field"><span>Join type</span><select id="join-type"><option value="inner" ${s.join==='inner'?'selected':''}>INNER JOIN · matching rows</option><option value="left" ${s.join==='left'?'selected':''}>LEFT JOIN · every item</option></select></label><label class="field"><span>Highlight a maker’s relationship</span><select id="highlight-maker">${MAKERS.map(row=>`<option value="${row.maker_id}" ${s.highlight===row.maker_id?'selected':''}>${row.maker_id} · ${esc(row.maker)}</option>`).join('')}</select></label><p class="section-note">This model requires non-NULL maker IDs. A nullable foreign key can permit NULL in SQL; NOT NULL is a separate rule.</p>`;
 $('#controls').oninput=()=>{s.id=$('#item-id').value;s.name=$('#item-name').value;s.quantity=$('#quantity').value;s.maker=$('#maker').value;s.enforce=$('#enforce-fk').checked;s.join=$('#join-type').value;s.highlight=Number($('#highlight-maker').value);updateKeys();};
 $('#controls').onclick=event=>{const preset=event.target.closest('[data-preset]')?.dataset.preset;if(!preset)return;s.id=preset==='duplicate'?'12340':String(Math.max(...s.items.map(row=>row.item_id))+1);s.maker=preset==='orphan'?'99':'2';s.message='Predict whether this row passes the constraints, then try INSERT.';s.error=false;renderKeys();};
 $('#insert-item').onclick=()=>{const outcome=insertItem(s.items,{item_id:s.id,item_name:s.name,item_qty:s.quantity,maker_id:s.maker},{enforceForeignKey:s.enforce});s.items=outcome.items;s.error=Boolean(outcome.error);s.message=outcome.error?`${outcome.constraint}: ${outcome.error} No row was added.`:`Inserted item ${s.id}. ${Number(s.maker)===99?'The orphan is visible because foreign-key enforcement is disabled.':'Its maker_id refers to an existing maker.'}`;updateKeys();};
 updateKeys();
}
function updateKeys(){
 const s=states.keys,joined=joinItems(s.items,s.join),orphans=s.items.filter(item=>!MAKERS.some(maker=>maker.maker_id===item.maker_id));
 result(`<div class="message ${s.error?'error':'success'}" role="status">${esc(s.message)}</div><section class="panel"><div class="panel-head"><h2>Identity → relationship</h2><span class="badge ${s.enforce?'':'error'}">FK ${s.enforce?'enforced':'disabled'}</span></div><div class="keys-grid">${modelTable('Items',['item_id','item_name','maker_id'],s.items,{highlight:row=>row[2]===s.highlight,warning:row=>row[2]===99})}${modelTable('Makers',['maker_id','maker'],MAKERS,{highlight:row=>row[0]===s.highlight})}</div><div class="relation"><code>Items.maker_id</code> → <code>Makers.maker_id</code><br><span class="hint">Many items can refer to the same maker. The referenced maker_id is unique.</span></div><div class="metrics"><span><strong>${s.items.length}</strong> items</span><span><strong>${MAKERS.length}</strong> makers</span><span><strong>${orphans.length}</strong> orphan${orphans.length===1?'':'s'}</span></div></section><section class="panel"><div class="panel-head"><h2>${s.join==='inner'?'INNER JOIN':'LEFT JOIN'} result</h2><span class="badge">${joined.length} rows</span></div>${table(['item_id','item_name','maker_id','maker'],joined.map(row=>[row.item_id,row.item_name,row.maker_id,row.maker]),{warning:row=>row[3]===null})}<p class="hint">${s.join==='inner'?'Only matching pairs appear. An orphan item has no matching maker and drops out.':'Every item remains. A missing maker produces NULL for columns on the right side.'}</p></section><div class="code-example"><pre>SELECT i.item_id, i.item_name, i.maker_id, m.maker
FROM items AS i
${s.join==='inner'?'INNER':'LEFT'} JOIN makers AS m ON m.maker_id = i.maker_id
ORDER BY i.item_id;</pre></div>`);
}

const NORMAL_FORMS=[{label:'Raw',title:'Repeating groups hide the relationship',description:'A list of jobs lives inside each employee row. Split each assignment into its own row.',dependency:['employee_id','list of job codes']},{label:'1NF',title:'One job assignment per row',description:'The composite key is (employee_id, job_code). Employee facts depend on employee_id alone; job names depend on job_code alone.',dependency:['employee_id + job_code','assignment row']},{label:'2NF',title:'Remove partial dependencies',description:'Employees, jobs, and assignments are separate. Employees still repeats the state name for everyone in the same state.',dependency:['employee_id','state_code','home_state']},{label:'3NF',title:'Remove the transitive dependency',description:'States owns the code-to-name relationship. Each employee stores a state code; a join supplies the state name.',dependency:['Employees.state_code','States.state_code']}];
function renderNormalization(){
 const s=states.normalization;
 $('#controls').innerHTML=`<h2>Follow the design</h2><div class="radio-row" aria-label="Normal form">${NORMAL_FORMS.map((form,index)=>`<button data-form="${index}" aria-pressed="${s.form===index}">${form.label}</button>`).join('')}</div><p class="compact">Changing the normal form resets the move, so each comparison begins with the same source data.</p><hr class="control-divider"><label class="field"><span>Move Alice · employee_id = 1</span><select id="new-state">${STATES.map(state=>`<option value="${state.state_code}" ${s.target===state.state_code?'selected':''}>${state.home_state} · ${state.state_code}</option>`).join('')}</select></label><div class="activity-buttons"><button class="primary" id="move-one">${s.form===1?'Update one assignment row':'Update Alice #1'}</button>${s.form===1?'<button id="move-all">Update every Alice #1 row</button>':''}<button id="reset-move">Reset move</button></div><p class="section-note">Alice #1 and Alice #3 are different employees with the same name. Use employee_id to choose one person.</p>`;
 $('#controls').onclick=event=>{const target=event.target.closest('[data-form]');if(target){s.form=Number(target.dataset.form);s.update='none';renderNormalization();}};
 $('#new-state').onchange=()=>{s.target=Number($('#new-state').value);s.update='none';updateNormalization();};
 $('#move-one').onclick=()=>{s.update='first';updateNormalization();};
 $('#move-all')?.addEventListener('click',()=>{s.update='all';updateNormalization();});
 $('#reset-move').onclick=()=>{s.update='none';updateNormalization();};
 updateNormalization();
}
function updateNormalization(){
 const s=states.normalization,view=normalizationView(s.form,s.update,s.target),form=NORMAL_FORMS[s.form];
 const status=view.anomaly?'Update anomaly: Alice #1 now has two different home states. One copy of the fact was missed.':s.update==='none'?'Original restaurant data from the lecture. Alice #1 lives in Michigan; Alice #3 lives in Wyoming.':`${view.affected} stored row${view.affected===1?'':'s'} updated for employee_id = 1. Alice #3 is unchanged.`;
 result(`<section class="panel"><div class="panel-head"><h2>${form.title}</h2><span class="badge">${form.label}</span></div><p class="compact">${form.description}</p><div class="dependency">${form.dependency.map((part,index)=>`${index?'<b aria-hidden="true">→</b>':''}<span><code>${part}</code></span>`).join('')}</div></section><div class="message ${view.anomaly?'error':'success'}" role="status">${status}</div><div class="normal-tables ${view.tables.length===1?'single':''}">${view.tables.map(data=>`<section class="table-card"><h3>${data.name}</h3><p class="key-note">Primary key: <code>${data.key}</code></p>${table(data.columns,data.rows,{highlight:row=>data.columns[0]==='employee_id'&&row[0]===1,warning:row=>view.anomaly&&row[0]===1})}</section>`).join('')}</div>${s.form>=2?`<section class="panel"><div class="panel-head"><h2>Join the facts back together</h2><span class="badge">5 assignments</span></div>${table(['employee_id','name','job','home_state'],view.joined.map(row=>[row.employee_id,row.name,row.job,row.home_state]),{highlight:row=>row[0]===1})}<p class="hint">Splitting the tables preserves the facts. Keys let us reconstruct the view when it is needed.</p></section>`:''}<p class="compact">This example assumes employee_id → name, state_code; job_code → job; and state_code → home_state. Normal forms follow these dependencies, not just the way a table looks.</p>`);
}

function schemaHTML(schema){return `<p class="schema-head">${schema.tables.length} TABLES / VIEWS · FOREIGN KEYS ${schema.foreignKeys?'ON':'OFF'}</p>${schema.tables.map(item=>`<details class="schema-details"><summary>${esc(item.name)} <span class="hint" style="display:inline">${item.type==='view'?'· view':''}</span></summary>${item.columns.map(column=>`<p class="schema-column">${esc(column.name)} <span class="badge">${esc(column.type)||'expression'}</span>${column.primaryKey?' · PK':''}${column.notNull?' · NOT NULL':''}</p>`).join('')}<pre>${esc(item.sql??'')}</pre></details>`).join('')}`;}
function sqlResultsHTML(response){
 const {results=[],error}=response;
 return `${error?`<div class="message error" role="alert"><strong>SQLite error</strong><br>${esc(error)}<br><span class="hint">Later statements did not run. Earlier statements may already have changed this tab’s database.</span></div>`:''}${results.map((set,index)=>`<section class="panel"><div class="panel-head"><h3>Statement ${index+1}</h3><span class="badge">${set.columns.length?`${set.values.length}${set.truncated?'+':''} rows`:`${set.changes} changed rows`}</span></div>${set.columns.length?table(set.columns,set.values):'<p class="compact">Statement completed.</p>'}${set.truncated?'<p class="result-meta">Display limited to the first 200 rows. Add LIMIT to choose a smaller result.</p>':''}</section>`).join('')}${!results.length&&!error?'<div class="message">No statements to display.</div>':''}`;
}
function renderQueries(){
 const s=states.queries,generation=renderGeneration;
 $('#controls').innerHTML=`<h2>Explore the schema</h2><label class="field"><span>Load an example</span><select id="query-example">${QUERY_EXAMPLES.map(example=>`<option value="${example.id}" ${s.example===example.id?'selected':''}>${esc(example.label)}</option>`).join('')}</select></label><button id="reset-data">Reset database</button><div id="q-schema"><p class="engine-loading">Loading local SQLite…</p></div><div class="dialect-note"><strong>SQLite in this browser.</strong> The lecture uses MySQL. CREATE DATABASE, USE, DESCRIBE, and MySQL connector placeholders do not work here. Use this schema panel or <code>PRAGMA table_info(employees)</code>. Ordinary SELECT, INSERT, UPDATE, DELETE, and JOIN examples are portable with dialect-specific details.<br><a href="https://www.sqlite.org/lang.html" target="_blank" rel="noopener">SQLite SQL reference ↗</a></div>`;
 result(`<section class="panel"><div class="editor-heading"><h2>Your SQL</h2><span class="engine-badge" id="engine-version">Engine starting</span></div><label class="sr-only" for="sql-editor">SQL statements</label><textarea class="sql-editor" id="sql-editor" spellcheck="false" maxlength="50000">${esc(s.sql)}</textarea><div class="sql-buttons"><button class="primary" id="run-sql" disabled>Run SQL →</button><button id="cancel-sql" hidden>Stop query</button><span class="hint">Ctrl / ⌘ + Enter · multiple statements allowed</span></div><p class="hint">This is a real, editable in-memory SQLite database. Changes remain while this activity is open. Reset restores the synthetic samples.</p></section><div id="query-output" class="sql-results" aria-live="polite"><div class="message">Loading the engine and the restaurant tables…</div></div>`);
 client=createSQLClient('queries',()=>{s.ready=false;s.busy=false;if(generation===renderGeneration)setQueryBusy(false);});
 function setQueryBusy(busy){s.busy=busy;$('#run-sql').disabled=busy||!s.ready;$('#cancel-sql').hidden=!busy;$('#reset-data').disabled=busy;}
 async function initialize(reset=false){
   s.ready=false;setQueryBusy(true);
   try{const response=await client.request(reset?'reset':'init');if(generation!==renderGeneration)return;s.ready=true;$('#q-schema').innerHTML=schemaHTML(response.schema);$('#engine-version').textContent=`SQLite ${response.schema.version} · local`;$('#query-output').innerHTML='<div class="message success">Database ready. Choose an example or edit the SQL above.</div>';}
   catch(error){if(generation===renderGeneration)$('#query-output').innerHTML=`<div class="message error" role="alert">${esc(error.message)} Use Reset database to retry.</div>`;}
   finally{if(generation===renderGeneration)setQueryBusy(false);}
 }
 async function run(){
   if(!s.ready||s.busy)return;s.sql=$('#sql-editor').value;setQueryBusy(true);$('#query-output').innerHTML='<div class="message">Running SQL locally…</div>';
   try{const response=await client.request('run',{sql:s.sql});if(generation!==renderGeneration)return;$('#query-output').innerHTML=sqlResultsHTML(response.result);$('#q-schema').innerHTML=schemaHTML(response.schema);}
   catch(error){if(generation===renderGeneration)$('#query-output').innerHTML=`<div class="message error" role="alert">${esc(error.message)}</div>`;}
   finally{if(generation===renderGeneration)setQueryBusy(false);}
 }
 $('#query-example').onchange=()=>{s.example=$('#query-example').value;s.sql=QUERY_EXAMPLES.find(example=>example.id===s.example).sql;$('#sql-editor').value=s.sql;$('#sql-editor').focus();};
 $('#sql-editor').oninput=()=>{s.sql=$('#sql-editor').value;};
 $('#sql-editor').onkeydown=event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();run();}};
 $('#run-sql').onclick=run;$('#cancel-sql').onclick=()=>client.cancel();$('#reset-data').onclick=()=>initialize(true);
 initialize();
}

function renderTransactions(){
 const s=states.transactions;
 $('#controls').innerHTML=`<h2>Plan a transfer</h2><label class="field"><span>Checking → savings · dollars</span><input id="transfer-amount" inputmode="decimal" value="${esc(s.amount)}" maxlength="12"></label><label class="check"><input id="fail-credit" type="checkbox" ${s.failCredit?'checked':''}>Simulate a constraint failure at credit</label><div class="activity-buttons"><button class="primary" id="tx-begin">1 · BEGIN</button><button id="tx-debit">2 · Debit checking</button><button id="tx-credit">3 · Credit savings</button><button class="primary" id="tx-commit">4 · COMMIT</button><button id="tx-rollback">ROLLBACK</button><button id="tx-reconnect">Reconnect model</button></div><p class="section-note">Amount and failure choice are captured at BEGIN. Money is modeled as integer cents. Only one transfer runs at a time.</p>`;
 $('#controls').oninput=()=>{s.amount=$('#transfer-amount').value;s.failCredit=$('#fail-credit').checked;};
 for(const action of ['begin','debit','credit','commit','rollback','reconnect'])$(`#tx-${action}`).onclick=()=>{s.model=transferAction(s.model,action,{amount:parseCents(s.amount),failCredit:s.failCredit});updateTransactions();};
 updateTransactions();
}
function money(cents){return `$${(cents/100).toFixed(2)}`;}
function balanceCard(title,balances,privateView=false){return `<div class="balance-card ${privateView?'private':''}"><h3>${title}</h3>${balances?`<div class="balance-row"><span>Checking</span><strong>${money(balances.checking)}</strong></div><div class="balance-row"><span>Savings</span><strong>${money(balances.savings)}</strong></div><div class="balance-total">Total: ${money(balances.checking+balances.savings)}</div>`:'<p class="empty">No active transaction.</p>'}</div>`;}
function updateTransactions(){
 const s=states.transactions,m=s.model;
 result(`${m.error?`<div class="message error" role="alert">${esc(m.error)}</div>`:''}<section class="panel"><div class="panel-head"><h2>What can each session see?</h2><span class="badge">${esc(m.phase)}</span></div><div class="split">${balanceCard('Committed · another reader sees this',m.committed)}${balanceCard('Private · the transfer’s working view',m.working,true)}</div><div class="transfer-flow">${[['begun','BEGIN'],['debited','debit'],['credited','credit'],['committed','COMMIT']].map(([phase,label])=>`<span class="${m.phase===phase?'active':''}">${label}</span>`).join('<span style="border:0;padding:8px 0" aria-hidden="true">→</span>')}</div><p class="hint">A temporary debit can appear in the working view. No partial transfer becomes committed. This model represents a reader that cannot see uncommitted writes.</p></section><section class="panel"><h2>Execution log</h2>${m.log.length?`<ol class="trace">${m.log.map((entry,index)=>`<li class="${index===m.log.length-1?'current':''}"><span class="trace-index">${index+1}</span><span>${esc(entry)}</span></li>`).join('')}</ol>`:'<p class="empty">Begin a transfer to see its steps.</p>'}<div class="acids"><div class="acid"><strong>A</strong><small>Both transfer changes commit together, or both are discarded.</small></div><div class="acid"><strong>C</strong><small>Checks enforce nonnegative balances and an unchanged transfer total.</small></div><div class="acid"><strong>I</strong><small>This reader sees committed values, not the private debit.</small></div><div class="acid"><strong>D</strong><small>Model reconnect retains the last committed values.</small></div></div></section><div class="code-example"><pre>BEGIN;
UPDATE accounts SET balance_cents = balance_cents - ?
WHERE account_id = 'checking';
UPDATE accounts SET balance_cents = balance_cents + ?
WHERE account_id = 'savings';
COMMIT;
-- Application catches a failure and issues ROLLBACK.</pre></div><p class="compact">This is a transaction model, not a bank or a disk-durability test. An SQL statement error does not universally roll back the entire transaction by itself; this model’s application explicitly does so. Actual isolation behavior depends on the database and isolation level. Reloading this browser page resets the experiment.</p>${source('https://www.sqlite.org/lang_transaction.html','SQLite transactions')}`);
 $('#tx-begin').disabled=Boolean(m.working);$('#tx-debit').disabled=m.phase!=='begun';$('#tx-credit').disabled=m.phase!=='debited';$('#tx-commit').disabled=m.phase!=='credited';$('#tx-rollback').disabled=!m.working;$('#transfer-amount').disabled=Boolean(m.working);$('#fail-credit').disabled=Boolean(m.working);
}

function renderETL(){
 const s=states.etl,generation=renderGeneration;
 $('#controls').innerHTML=`<h2>Extract the source</h2><label class="field"><span>JSON employee records</span><textarea id="etl-json" class="etl-json" spellcheck="false" maxlength="60000">${esc(s.raw)}</textarea></label><label class="check"><input id="trim-names" type="checkbox" ${s.trimNames?'checked':''}>Trim names</label><label class="check"><input id="normalize-states" type="checkbox" ${s.normalizeStates?'checked':''}>Trim & uppercase state abbreviations</label><label class="field"><span>Duplicate IDs within this batch</span><select id="duplicate-policy"><option value="skip" ${s.duplicates==='skip'?'selected':''}>Keep first valid ID</option><option value="reject" ${s.duplicates==='reject'?'selected':''}>Block the whole batch</option></select></label><div class="activity-buttons"><button class="primary" id="load-batch" disabled>Load accepted rows →</button><button id="reset-etl-db" disabled>Reset SQL table</button></div><p class="section-note">Known states: MI = 26, WY = 56, VA = 51. Numeric state codes are accepted. Source data is synthetic.</p>`;
 client=createSQLClient('etl',()=>{s.ready=false;s.busy=false;if(generation===renderGeneration)updateETL();});
 $('#controls').oninput=()=>{s.raw=$('#etl-json').value;s.trimNames=$('#trim-names').checked;s.normalizeStates=$('#normalize-states').checked;s.duplicates=$('#duplicate-policy').value;updateETL();};
 async function initialize(reset=false){s.busy=true;updateETL();try{const response=await client.request(reset?'reset':'init');if(generation!==renderGeneration)return;s.ready=true;s.imported=response.imported;s.message=reset?'SQL table reset. The JSON source is unchanged.':'SQLite table ready. Inspect the preview, then load the accepted rows.';s.error=false;}catch(error){if(generation===renderGeneration){s.message=error.message;s.error=true;}}finally{if(generation===renderGeneration){s.busy=false;updateETL();}}}
 $('#load-batch').onclick=async()=>{
   const transformed=transformEmployees(s.raw,s);if(transformed.error||!s.ready||s.busy)return;s.busy=true;updateETL();
   try{const response=await client.request('load',{records:transformed.accepted});if(generation!==renderGeneration)return;s.imported=response.imported;s.error=Boolean(response.result.error);s.message=response.result.error?`Batch rolled back: ${response.result.error}. No rows from this load were kept.`:`Committed ${response.result.loaded} accepted rows with bound parameters.`;}
   catch(error){if(generation===renderGeneration){s.message=error.message;s.error=true;}}
   finally{if(generation===renderGeneration){s.busy=false;updateETL();}}
 };
 $('#reset-etl-db').onclick=()=>initialize(true);initialize();
}
function updateETL(){
 const s=states.etl,view=transformEmployees(s.raw,s);
 result(`<section class="panel"><div class="panel-head"><h2>Extract → transform → load</h2><span class="badge">${s.busy?'Working…':s.ready?'SQLite ready':'Engine starting'}</span></div><div class="etl-flow"><div class="flow-node">JSON input<strong class="etl-count">${view.source.length}</strong><span class="sub">source records</span></div><div class="flow-node ${view.rejected.length?'orange':'active'}">Validate / transform<strong class="etl-count">${view.accepted.length}</strong><span class="sub">accepted records</span></div><div class="flow-node blue">SQL storage<strong class="etl-count">${s.imported.values.length}</strong><span class="sub">committed rows</span></div></div></section>${view.error?`<div class="message error" role="alert">${esc(view.error)}</div>`:''}<section class="panel"><div class="panel-head"><h2>Accepted preview</h2><span class="badge">${view.accepted.length} rows</span></div>${table(['employee_id','name','state_code'],view.accepted.map(row=>[row.employee_id,row.name,row.state_code]))}<p class="hint">Preview does not write data. Names remain data even if they contain apostrophes or SQL-looking text.</p></section>${view.rejected.length?`<section class="panel"><div class="panel-head"><h2>Rejected records</h2><span class="badge error">${view.rejected.length}</span></div><ul class="etl-rejected">${view.rejected.map(item=>`<li><b>SOURCE ROW ${item.row}</b>${esc(item.reason)}</li>`).join('')}</ul></section>`:''}<div class="message ${s.error?'error':'success'}" role="status">${esc(s.message)}</div><section class="panel"><h2>Stored: imported_employees</h2>${table(s.imported.columns,s.imported.values)}<p class="hint">All accepted rows from one load commit together. A conflict with an already stored employee_id rolls back that entire load.</p></section><div class="code-example"><pre># Python sqlite3 · all accepted rows in one transaction
with connection:
    connection.executemany(
        "INSERT INTO imported_employees "
        "(employee_id, name, state_code) VALUES (?, ?, ?)",
        [(r["employee_id"], r["name"], r["state_code"])
         for r in accepted]
    )</pre></div><p class="compact">The browser loader uses equivalent bound SQLite parameters. MySQL Connector/Python uses <code>%s</code> placeholders instead of <code>?</code>; the values still travel separately from SQL text.</p>`);
 $('#load-batch').disabled=!s.ready||s.busy||Boolean(view.error)||view.accepted.length===0;$('#reset-etl-db').disabled=s.busy;
}
const renderers={keys:renderKeys,normalization:renderNormalization,queries:renderQueries,transactions:renderTransactions,etl:renderETL};
window.addEventListener('pagehide',()=>client?.close());
render();
